# Generated by Django 4.1.7 on 2023-05-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.CharField(blank=True, max_length=50, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='product')),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
