# Generated by Django 4.1.7 on 2023-06-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_username', models.CharField(blank=True, max_length=50, null=True)),
                ('c_pname', models.CharField(blank=True, max_length=50, null=True)),
                ('c_description', models.CharField(blank=True, max_length=50, null=True)),
                ('c_quantity', models.IntegerField(blank=True, null=True)),
                ('c_price', models.IntegerField(blank=True, null=True)),
                ('c_totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
