# Generated by Django 4.1.7 on 2023-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart'),
        ),
    ]
