# Generated by Django 4.1.7 on 2023-06-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb_c_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='c_image',
        ),
    ]
