# Generated by Django 4.1.7 on 2023-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_cartdb_c_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ck_fname', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_lname', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('ck_country', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_district', models.CharField(blank=True, max_length=50, null=True)),
                ('ck_pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
