# Generated by Django 4.1.7 on 2023-06-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='ck_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='ck_town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
